### ISSUE TITLE
US 02.02.01: Add comment on QR Codes

### ISSUE THREAD

**Issue by MSNanda515** [CMPUT301W23T47/Canary#10]
AS a player, I WANT to be able to comment on QR codes.

## Description
The player can comment on QR codes. They should have an option where they can add a comment during the scan QR code workflow. Alternatively, they can also add a comment when they choose a QR Code from their list of scanned QR Codes (US 01.02.01). Additionally, the player can also comment on QR codes scanned by other players (US 01.07.01). The player can post multiple comments on a QR Code.

## Acceptance criteria
- [ ] The player is provided an interface to add a comment when scanning a new QR Code
- [ ] The player is provided an interface to add a comment on their old scanned QR Codes. 
- [ ] The player is provided an interface to add a comment on QR Codes scanned by other players. 
- [ ] The player can post multiple comments on a QR code.

## Tasks
- [x] #33
