### ISSUE TITLE
US 02.04.01: View other players who scanned same QR Code

### ISSUE THREAD

**Issue by MSNanda515** [CMPUT301W23T47/Canary#12]
AS a player, I WANT to see that other players who have scanned the same QR code.

## Description
The player is provided with an interface that allows them to view the list of players who have scanned the selected QR Code. The player should be able to navigate to the other player's profile if they choose to. The list should include details about the player and when they scanned the given QR Code. The list should be sorted in descending order (the most recent scan at the top).

## Acceptance criteria
- [ ] The player can view all the players who have scanned the given QR Code.
- [ ] The player can navigate to the selected player's profile from the list.
- [ ] Detail about the player and when they scanned should be present
- [ ] The list should be sorted in descending order
- [ ] The page should clearly specify details about the selected QR Code.

## Tasks
- [x] #36 
- [x] #48
