### ISSUE TITLE
US 04.01.01: Player has a profile

### ISSUE THREAD

**Issue by MSNanda515** [CMPUT301W23T47/Canary#15]
AS a player, I WANT a profile with a unique username and contact information.

## Description
The player has a profile that includes the player's unique username (case insensitive) (STC) and contact information.

## Acceptance criteria
- [ ] There is an interface that allows the player to create their profile
- [ ] There is an interface that allows the player to view their profile
- [ ] The username should have a unique value

## Tasks
- [x] #39 
- [x] #56 
- [ ] #91
