### ISSUE TITLE
US 04.02.01: Player identified by their device

### ISSUE THREAD

**Issue by MSNanda515** [CMPUT301W23T47/Canary#16]
AS a player, I DO NOT WANT to log into my application using a username and password as my device can identify me.

## Description
The player is identified by their device. The user shouldn't have to log into the application using a username and password. A new device will mean a new player (STC).

## Acceptance criteria
- [x] The player can be identified by their device.
- [ ] The player doesn't have to log in using their username and password.
- [x] New device implies a new player. (TODO Link)

## Tasks
- [x] #82
