### ISSUE TITLE
US 05.01.01: Search for players using Username

### ISSUE THREAD

**Issue by MSNanda515** [CMPUT301W23T47/Canary#17]
AS a player, I WANT to search for other players by username.

## Description
The player can search for other players using their usernames. The search should include results with partial matches (Eg. "cd" matches with "abcd") . The search is case insensitive (STC). The result with complete matching should appear at the top, followed by partial matches (STC). There is an interface to navigate to the selected player's profile.

## Acceptance criteria
- [ ] The player can search for players using their username.
- [ ] The search includes results with partial substrings.
- [ ] The result with a complete match to the query appears at the top of the list.
- [ ] There is an interface to navigate to the selected player's profile.

## Tasks
- [x] #30 
- [x] #55
