### ISSUE TITLE
US 05.02.01: Search nearby QR Codes.

### ISSUE THREAD

**Issue by MSNanda515** [CMPUT301W23T47/Canary#18]
AS a player, I WANT to search for nearby QR codes by using geolocation.

## Description
The player can search nearby QR Codes by setting a search radius. The results should ideally appear on a Map interface. Alternatively, the results can be shown in list form. The results should include information like distance to the location and the date when it was last scanned. The list shouldn't include those QR Codes that have already been scanned by the player.

## Acceptance criteria
- [ ] The player can set a search radius
- [ ] The results should include information like distance and last scanned date of QR Code.
- [ ] The results don't include the QR codes already scanned.

## Tasks
- [x] #40 
- [x] #59
- [ ] #90
