### ISSUE TITLE
US 06.01.01: View nearby QR Codes on map

### ISSUE THREAD

**Issue by MSNanda515** [CMPUT301W23T47/Canary#19]
As a player, I want to see a map of geo-locations of nearby QR codes.

## Description
The player can view the nearby QR Codes on a map using geolocation. The query param for nearby should be configurable. The list shouldn't include QR Codes already scanned by the player (STC). 

## Acceptance criteria
- [ ] The player can view the nearby QR Codes on a map.
- [ ] The query parameter for nearby can be easily configured.
- [ ] The map doesn't include QR Codes already scanned (STC).

## Tasks
- [x] #41 
- [x] #58
