### ISSUE TITLE
US 01.01.01: Add new QR Code

### ISSUE THREAD

**Issue by MSNanda515** [CMPUT301W23T47/Canary#2]
AS a player, I WANT to be able to add new QR-Codes to my profile SO THAT I earn more points.

## Description
The player should be provided an interface that allows them to scan QR code. The scanned QR code is persisted to track the QR codes scanned by the player. The player should be told if the QR Code is already scanned by the user. They only get the points if they haven't scanned it before.

## Acceptance criteria
- [ ] There is an interface that allows the user to scan the QR code
- [ ] The hash for the scanned QR code is persisted
- [ ] Player gets the score for QR code scan if they haven't scanned it before.
- [ ] Player is told if they have already scanned the QR Code before.

## Tasks
- [x] #49 
- [x] #50 
- [x] #57 
- [ ] #95
- [ ] #86

**Comment by bc-davin** [comment]
We have completed this task.
