### ISSUE TITLE
US 07.01.01: View game-wide high scores

### ISSUE THREAD

**Issue by MSNanda515** [CMPUT301W23T47/Canary#20]
AS a player, I WANT to see game-wide high scores from all players.

## Description
The player can view the game-wide high scores among all players. The players are ranked in the order of their high scores (in descending order by score). The leaderboard should be paginated to show 20-30 players on a page.

## Acceptance criteria
- [ ] The player can view the leaderboard.
- [ ] The leaderboard is paginated.
- [ ] The leaderboard should update in real-time (STC).

## Tasks
- [x] #42 
- [x] #60
