### ISSUE TITLE
US 07.02.01: View player's ranking for Highest scoring QR Code

### ISSUE THREAD

**Issue by MSNanda515** [CMPUT301W23T47/Canary#21]
AS a player, I WANT an estimate of my ranking for the highest-scoring unique QR code.

## Description
The player can view their ranking for the ranking of their highest scoring QR Code. (Players ranked by their highest scoring QR Code) (STC). 

## Acceptance criteria
- [ ] The leaderboard has a view for showing the ranking for the highest scoring QR Code.
- [ ] The metric doesn't have to update in real-time (can be an estimate).
- [ ] Refresh the metric for the player fairly often.

## Tasks
- [x] #43 
- [x] #60
