### ISSUE TITLE
US 01.02.01: View past QR codes

### ISSUE THREAD

**Issue by MSNanda515** [CMPUT301W23T47/Canary#3]
AS a player, I WANT to view the QR codes scanned in the past.

## Description
The player should be provided with an interface that allows them to view the QR codes scanned in the past. The player should be provided with an interface that allows them to see all information available about the scanned QR code such as the date, time, location, photo, and score.

## Acceptance criteria
- [ ] There is an interface for viewing the QR codes scanned in the past
- [ ] The individual fields for the QR code are immutable. 
- [ ] Summarized information about the QR Code is visible at a glance

## Tasks
- [x] #28 
- [x] #83 
- [ ] #88
