### ISSUE TITLE
US 01.03.01: Delete past QR codes

### ISSUE THREAD

**Issue by MSNanda515** [CMPUT301W23T47/Canary#4]
AS a player, I WANT to remove QR codes from my account.

## Description
The player should be able to delete selected QR codes from their account. Their score should be updated to reflect the change. Moreover, it should be enforced that the player can only delete QR codes from their own account.

## Acceptance criteria
- [ ] Their is an interface for deleting a QR Code from the player's profile.
- [ ] The player should be prompted to confirm their request before deleting the QR Code.
- [ ] The player's score should update to reflect the change.
- [ ] The player can only delete QR Code from their own profile.

## Tasks
- [x] #27 
- [x] #52 
- [ ] #87
