### ISSUE TITLE
US 01.04.01: View highest and lowest scoring QR code

### ISSUE THREAD

**Issue by MSNanda515** [CMPUT301W23T47/Canary#5]
AS a player, I WANT to see my highest and lowest-scoring QR codes.

## Description
The player should be provided an interface that allows them to view their highest and lowest-scoring QR codes. The player should be able to view detailed information (such as date, location, etc.) about these QR Codes if they wish to expand them.

## Acceptance criteria
- [ ] There is an interface that shows the highest and lowest-scoring QR Codes
- [ ] There is an interface allowing the player to view details about the QR Codes.
- [ ] Some details such as the score are available at a glance.

## Tasks
- [x] #29 
- [x] #56
