### ISSUE TITLE
US 01.05.01: View Total Score

### ISSUE THREAD

**Issue by MSNanda515** [CMPUT301W23T47/Canary#6]
AS a player, I WANT to see the sum of the scores of QR codes I have scanned.

## Description
The player should be able to view the total score of the scanned QR codes at a glance. 

## Acceptance criteria
- [ ] There is an interface that shows the total score of the scanned QR Codes.
- [ ] The value should update immediately whenever a new QR code is added/removed.
- [ ] Should be visible on the main screen

## Tasks
- [x] #31 
- [x] #56
