### ISSUE TITLE
US 01.06.01: View Number of codes scanned

### ISSUE THREAD

**Issue by MSNanda515** [CMPUT301W23T47/Canary#7]
AS a player, I WANT to see the total number of QR codes that I have scanned.

## Description
The player should be able to view the total number of QR codes scanned by the player.

## Acceptance criteria
- [ ] There is an interface that shows the number of QR codes scanned by the player
- [ ] The value should update immediately whenever a new QR code is added/removed.
- [ ] Should be visible on the main screen

## Tasks
- [x] #32  
- [x] #56
