### ISSUE TITLE
US 01.07.01: View Other people's profiles

### ISSUE THREAD

**Issue by MSNanda515** [CMPUT301W23T47/Canary#8]
AS a player, I WANT to see other player’s profiles

## Description
The player should be able to view a list of other players. Upon selecting a player, their profile should be shown. The following information should be visible in their profile: Username, scanned QR Codes, Total points, and the number of scanned QR codes. 

## Acceptance criteria
- [ ] There is an interface that lists all the other players
- [ ] The player can search for a given player using their Username
- [ ] The selected player's profile can be viewed (includes Username, Scores, and list of scanned QR Codes).
- [ ] The other player's information cannot be modified by a different player

## Tasks
- [x] #30 
- [x] #54 
- [x] #55
- [ ] #89
