### ISSUE TITLE
US 02.01.01: Record Photo and geolocation for QR Code

### ISSUE THREAD

**Issue by MSNanda515** [CMPUT301W23T47/Canary#9]
AS a player, I WANT to be able to scan QR codes and record a photo of the location or object, and the geolocation of the location or object.

## Description
The player should be prompted to take a picture of the object/location of the QR Code once they scan it. They should then be prompted to save the geolocation of the object/location with the QR code. The player can choose not to record these two fields.

## Acceptance criteria
- [ ] The player is prompted to add a picture from the camera once they add a QR code.
- [ ] The player can add a piture from the camera after the prompt.
- [ ] The player is prompted to record the geolocation of the object/location with the QR code.
- [ ] The player can save the geolocation
- [ ] The player can choose not to record the photo or geolocation or both.

## Tasks
- [x] #34 
- [ ] #86
